# version: '3'
# services:
#   mongodb:
#     image: mongo:6
#     restart: unless-stopped
#     ports:
#       - "${FORWARD_MONGO_PORT:-27018}:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#       MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#     volumes:
#       - ./docker/mongodb:/data/db
